In [7]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
data = pd.read_csv('E:\ML projects - Copy\IPL Match Predictor 🏏\matches.csv')
df = pd.DataFrame(data)

In [9]:
df.shape

(1095, 20)

In [10]:
df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

In [11]:
df.head()

       id   season        city  ... method    umpire1         umpire2
0  335982  2007/08   Bangalore  ...    NaN  Asad Rauf     RE Koertzen
1  335983  2007/08  Chandigarh  ...    NaN  MR Benson      SL Shastri
2  335984  2007/08       Delhi  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985  2007/08      Mumbai  ...    NaN   SJ Davis       DJ Harper
4  335986  2007/08     Kolkata  ...    NaN  BF Bowden     K Hariharan

[5 rows x 20 columns]

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 171.2 KB

In [13]:
df.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [14]:
df['winner'].isnull().sum()

np.int64(5)

In [15]:
df['team1'].unique()

<StringArray>
['Royal Challengers Bangalore',             'Kings XI Punjab',
            'Delhi Daredevils',              'Mumbai Indians',
       'Kolkata Knight Riders',            'Rajasthan Royals',
             'Deccan Chargers',         'Chennai Super Kings',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',               'Gujarat Lions',
     'Rising Pune Supergiants',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
        'Lucknow Super Giants',              'Gujarat Titans',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

In [16]:
df['team1'].value_counts()

team1
Royal Challengers Bangalore    135
Chennai Super Kings            128
Mumbai Indians                 123
Kolkata Knight Riders          121
Rajasthan Royals               101
Kings XI Punjab                 92
Sunrisers Hyderabad             86
Delhi Daredevils                85
Delhi Capitals                  41
Deccan Chargers                 39
Punjab Kings                    31
Pune Warriors                   23
Lucknow Super Giants            23
Gujarat Titans                  21
Gujarat Lions                   16
Royal Challengers Bengaluru      9
Kochi Tuskers Kerala             7
Rising Pune Supergiants          7
Rising Pune Supergiant           7
Name: count, dtype: int64

In [17]:
df['toss_decision'].value_counts()

toss_decision
field    704
bat      391
Name: count, dtype: int64

In [18]:
df['venue'].nunique()

58

In [19]:
team_name_mapping = {
    'Delhi Daredevils': 'Delhi Capitals', 'Kings XI Punjab': 'Punjab Kings', 'Rising Pune Supergiant': 'Rising Pune Supergiants', 'Royal Challengers Bangalore':'Royal Challengers Bengaluru'
}

for col in ['team1', 'team2','toss_winner', 'winner']:
    df[col] = df[col].replace(team_name_mapping)

In [20]:
df['team1'].value_counts()

team1
Royal Challengers Bengaluru    144
Chennai Super Kings            128
Delhi Capitals                 126
Punjab Kings                   123
Mumbai Indians                 123
Kolkata Knight Riders          121
Rajasthan Royals               101
Sunrisers Hyderabad             86
Deccan Chargers                 39
Pune Warriors                   23
Lucknow Super Giants            23
Gujarat Titans                  21
Gujarat Lions                   16
Rising Pune Supergiants         14
Kochi Tuskers Kerala             7
Name: count, dtype: int64

In [21]:
df = df.dropna(subset = ['winner'])

columns_to_keep = ['team1','team2','venue','toss_winner','toss_decision','winner']
df = df[columns_to_keep]

In [22]:
print(df.shape)
df.isnull().sum()

(1090, 6)

team1            0
team2            0
venue            0
toss_winner      0
toss_decision    0
winner           0
dtype: int64

In [28]:
from sklearn.preprocessing import LabelEncoder
encoder_team = LabelEncoder()
encoder_venue = LabelEncoder()
encoder_toss = LabelEncoder()

all_teams = pd.concat([df['team1'], df['team2'], df['toss_winner'], df['winner']])
encoder_team.fit(all_teams)

df['team1'] = encoder_team.transform(df['team1'])
df['team2'] = encoder_team.transform(df['team2'])
df['toss_winner'] = encoder_team.transform(df['toss_winner'])
df['winner'] = encoder_team.transform(df['winner'])
df['venue'] = encoder_venue.fit_transform(df['venue'])
df['toss_decision'] = encoder_toss.fit_transform(df['toss_decision'])
df.head()

   team1  team2  venue  toss_winner  toss_decision  winner
0     13      6     23           13              1       6
1     10      0     40            0              0       0
2      2     11     16           11              0       2
3      8     13     55            8              0      13
4      6      1     14            1              0       6

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X = df.drop(columns = ['winner'])
y = df['winner']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred_rf)
print(f"Random forest Accuracy { accuracy*100:.2f}%")

Random forest Accuracy 53.21%